In [1]:
#################################
# Convolution operation in Python
#################################
# 1.1 Load the libraries
#
from scipy import signal as sg
#################################
# Example#1
# 2 dimensional Convolution
#
I = [[97,52,99,62,69,45,70],[99,14,60,50,74,45,22],[59,72,74,14,74,100,28],[28,8,47,85,2,88,77],[28,8,47,85,2,88,77],[86,87,4,53,36,10,46],[54,7,67,23,29,26,15]]
g = [[1,2,1],[2,4,2],[1,2,1]]

In [2]:
sg.convolve(I,g)



array([[  97,  246,  300,  312,  292,  245,  229,  185,   70],
       [ 293,  704,  787,  808,  818,  733,  644,  459,  162],
       [ 354,  860,  951,  914,  936,  993,  903,  519,  142],
       [ 245,  656,  832,  839,  805,  944, 1045,  643,  155],
       [ 143,  382,  550,  795,  833,  793, 1067,  882,  259],
       [ 170,  451,  537,  709,  803,  666,  867,  828,  277],
       [ 254,  697,  754,  647,  653,  554,  555,  502,  184],
       [ 194,  489,  534,  476,  430,  349,  294,  214,   76],
       [  54,  115,  135,  164,  142,  107,   96,   56,   15]])

In [3]:
sg.convolve(I,g,"valid")


array([[ 951,  914,  936,  993,  903],
       [ 832,  839,  805,  944, 1045],
       [ 550,  795,  833,  793, 1067],
       [ 537,  709,  803,  666,  867],
       [ 754,  647,  653,  554,  555]])

In [4]:
sg.convolve(I,g,"valid")


array([[ 951,  914,  936,  993,  903],
       [ 832,  839,  805,  944, 1045],
       [ 550,  795,  833,  793, 1067],
       [ 537,  709,  803,  666,  867],
       [ 754,  647,  653,  554,  555]])

In [5]:
############################################### 
# Convolution operation in Python and TensorFlow 
################################################ 
# 1.1 Load the libraries
#
import tensorflow as tf 
################################################ 
input_list = tf.constant( [
[ 1., 4., 6, 10, 14, 12], 
    [18, 20, 26, 25, 13, 10], 
    [ 6, 5, 4, 3, 1, 2], 
    [ 2, 4, 5, 10, 12, 26], 
    [38, 25, 49, 24, 26, 30], 
    [ 2, 40, 36, 44, 25, 13] ])

In [19]:
input_list.shape

TensorShape([7, 7])

In [20]:
input = tf.reshape(input_list,[1,6,6,1])


InvalidArgumentError: Input to reshape is a tensor with 49 values, but the requested shape has 36 [Op:Reshape]

In [21]:
filter_list = tf.constant ([ [1.,2.,1.],
      [2,4,2],
      [1,2,1] ])


In [22]:
filter_list.shape

TensorShape([3, 3])

In [23]:
filter = tf.reshape(filter_list,[3,3,1,1])

In [24]:
filter.shape

TensorShape([3, 3, 1, 1])

In [25]:
#######################################################
op1 = tf.nn.conv2d(input,filter,strides=[1,1,1,1], padding='VALID') 
op2 = tf.nn.conv2d(input,filter,strides=[1,1,1,1], padding='SAME')

In [26]:
print(op1)

tf.Tensor(
[[[[203.]
   [236.]
   [229.]
   [179.]]

  [[139.]
   [153.]
   [148.]
   [135.]]

  [[187.]
   [211.]
   [208.]
   [233.]]

  [[407.]
   [474.]
   [432.]
   [379.]]]], shape=(1, 4, 4, 1), dtype=float32)


In [27]:
print(op2)

tf.Tensor(
[[[[ 68.]
   [114.]
   [149.]
   [169.]
   [161.]
   [109.]]

  [[135.]
   [203.]
   [236.]
   [229.]
   [179.]
   [109.]]

  [[ 98.]
   [139.]
   [153.]
   [148.]
   [135.]
   [107.]]

  [[134.]
   [187.]
   [211.]
   [208.]
   [233.]
   [219.]]

  [[254.]
   [407.]
   [474.]
   [432.]
   [379.]
   [287.]]

  [[189.]
   [373.]
   [459.]
   [421.]
   [320.]
   [188.]]]], shape=(1, 6, 6, 1), dtype=float32)
